services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: web_container
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
  
  celery:
    build: .
    command: celery -A multi_user_blog_platform worker --loglevel=info
    container_name: celery_container
    depends_on:
      - redis
      - db
      - web
    volumes:
      - .:/app

volumes:
  postgres_data: