# Generated by Django 5.2.4 on 2025-07-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_appuser_date_joined_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Pet',
        ),
    ]
