# Generated by Django 5.2.4 on 2025-07-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_rename_profile_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='first_name',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, default='Hello there', max_length=500, null=True),
        ),
    ]
