# Generated by Django 5.2.4 on 2025-07-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_rename_first_name_pet_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='specie',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
